### ISSUE TITLE
Nice theme, 1 remark

### ISSUE THREAD

**Issue by riemers** [aFFekopp/noctis#1]
![image](https://user-images.githubusercontent.com/682041/72562741-6946cf00-38ac-11ea-8c3a-7808c0901dc4.png)

Only if you hover over will you see the icons. I don't know if its possible since they overlap most of the time..

**Comment by aFFekopp** [comment]
There doesn't seem to be a way to change the background color of that dropdown. I have made the icons slightly darker so you can at least see them.

**Comment by riemers** [comment]
I see that issue with a lot of themes though. It looks really nice on the main page but then other stuff break. Maybe it will change in the future but the slight change is sufficient to see them indeed.
