### ISSUE TITLE
App header colour is incorrect

### ISSUE THREAD

**Issue by aptonline** [aFFekopp/noctis#10]
After much investigation the header (status bar for the iOS app) colour is set to the `accent-color` and it should be set to `primary-color` as per docs.

https://companion.home-assistant.io/en/integrations/theming

**Comment by aFFekopp** [comment]
What does the ios header look like right now? I don't have the app to test it.

**Comment by aptonline** [comment]
It’s set as the light blue accent-color.

This is the amendment I made to fix it:

 `primary-color: '#242e42'`

**Comment by aptonline** [comment]
Just upgraded to 1.9 to show you the problem:

![4541A558-E513-4A0E-99C6-34C500163435](https://user-images.githubusercontent.com/190136/72944638-6434c480-3d71-11ea-9779-12309a603db2.jpeg)

**Comment by aptonline** [comment]
Btw has to use hex not a colour variable.

**Comment by aFFekopp** [comment]
I had the `primary-color` the same as the `background-color` before. And then changed it because it broke some other cards see #6 

I couldn't find a way to change those sliders, because they use `primary-color`.

I think using `primary-color` for the header color in the ios app is not a good choice.

**Comment by aptonline** [comment]
But the docs state that’s the colour that’s used for the header. Ideally there need to be an `app-header-color` that’s separate.

**Comment by aFFekopp** [comment]
Yes i think that would be a better way, just like some lovelace cards have their own theme variables.

**Comment by aFFekopp** [comment]
There is already an [open issue](https://github.com/home-assistant/home-assistant-iOS/issues/531) in the repository of the ios app for this problem

**Comment by aptonline** [comment]
Until that’s investigated I’ve added the above fix to my install of `noctis`. it doesn’t seem to affect any other aspect of the theme to any great detriment.

**Comment by aFFekopp** [comment]
Has been fixed in the latest iOS App. https://github.com/home-assistant/home-assistant-iOS/commit/e25ca84e72f45f6c9c41de900c011d090231aa06
