### ISSUE TITLE
Your lovelace config

### ISSUE THREAD

**Issue by alex3305** [aFFekopp/noctis#11]
Hi,

Thanks for the theme. It looks really nice, especially how you have configured it in your screenshots. Details on your configuration are a bit sparse though. Can you provide us (with part) of your Lovelace config, or at least mention the plugins that you have used to create those beautiful images.

Thanks!

**Comment by aFFekopp** [comment]
My config is also available on GitHub https://github.com/aFFekopp/homeassistant

Check out the [readme](https://github.com/aFFekopp/homeassistant/blob/master/README.md). There you can also find the plugins I am using.

**Comment by alex3305** [comment]
Right. I've certainly missed that. Sorry to bother you and thanks again for the great work!
