### ISSUE TITLE
HACS?

### ISSUE THREAD

**Issue by shkm** [aFFekopp/noctis#12]
You mention installing via HACS but I'm not able to find Noctis on the store (after updating). Are you aware of this, or is it on my side?

**Comment by aFFekopp** [comment]
Must be on your side? For me it's showing up just fine. Do you see all the other themes in hacs? Did you try to ```reload data``` in hacs?

**Comment by shkm** [comment]
Hey, yeah, sorry for wasting your time here. I'm not sure what was up, but I didn't have a themes tab. Reinstalled HACS and all is well. Thanks!
