### ISSUE TITLE
Lovely theme, but blinds aren't showing correctly

### ISSUE THREAD

**Issue by fribse** [aFFekopp/noctis#13]
With blinds there are two arrows and a stop button (up/down/stop), and a bar that shows how much light is coming in.
With this theme, the color diffentiation on the the up/down arrows are so miniscule that it's impossible to see when the blind is fully up/down.
Neither are there any clear marking of the amount of light (usually the horizontal bar has a color that shows it, but not here).
Here the darkish theme:
![blue-1](https://user-images.githubusercontent.com/13660621/80179955-ec8d6480-8601-11ea-933a-0c1162867709.png)
![blue-2](https://user-images.githubusercontent.com/13660621/80179959-ef885500-8601-11ea-86a1-5234a675735a.png)
Here the noctis theme:
![noctis-1](https://user-images.githubusercontent.com/13660621/80179987-00d16180-8602-11ea-9ebe-5f5f63feb34e.png)
![noctis-2](https://user-images.githubusercontent.com/13660621/80179991-0333bb80-8602-11ea-9ef1-08fa40cf9e0d.png)

**Comment by aFFekopp** [comment]
I have changed the sliders and the ```disabled-text-color``` in the latest release ( [2.2](https://github.com/aFFekopp/noctis/releases/tag/2.2) ). See if this fixes your problems.

**Comment by fribse** [comment]
Yes, that fixed it, perfect, thankyou, and thankyou for the lovely theme :-)
