### ISSUE TITLE
hui-view-settings.js:18 Uncaught (in promise) ReferenceError: fireEvent is not defined at hui-view-settings.js:18

### ISSUE THREAD

**Issue by poldim** [aFFekopp/noctis#14]
I'm getting an error in chrome when I bring up the UI: 

```
hui-view-settings.js:18 Uncaught (in promise) ReferenceError: fireEvent is not defined
    at hui-view-settings.js:18
```

I've tried removing my entire lovelace config and just showing a single glances card, but this still comes up.

The reference points to line 18 in the `hui-view-settings.js`
https://github.com/aFFekopp/noctis/blob/2a08accc4afbb1d76faa738390a363c10be2ff5d/www/hui-view-settings.js#L18

![image](https://user-images.githubusercontent.com/16869713/80257691-558ecf80-8636-11ea-8ba9-9203cc9597e3.png)

![image](https://user-images.githubusercontent.com/16869713/80257879-bb7b5700-8636-11ea-89c0-c9210b8637ff.png)

**Comment by aFFekopp** [comment]
I had uploaded the wrong file, it should be:

```
customElements.whenDefined("hui-view").then( () => {
  const HuiView = customElements.get("hui-view").prototype;
  const oldRenderStyles = HuiView.renderStyles;
  HuiView.renderStyles = function() {
    let original = oldRenderStyles();
    original.strings = [original.strings[0] + `
    <style>
      .column {
        overflow: unset !important;
        padding-left: 9px;
        padding-right: 9px;
        padding-bottom: 9px;
      }
    </style>
    `];
    return original;
  }
});
```

Without the fireEvent stuff.

I hope that fixes it for you. I don't mention this file in the readme, it's just something i use to add a bit of padding around the whole lovelace view.

I got it from [here](https://community.home-assistant.io/t/my-2020-redesigned-lovelace-setup-and-some-automations/160558/16?u=affekopp), I don't fully understand how it works 😃
