### ISSUE TITLE
Red severity on gauge card has incorrect colour

### ISSUE THREAD

**Issue by Draxter** [aFFekopp/noctis#18]
Theme Version 2.4
HA Version: 0.113.3

The the red severity in the gauge card does not show as red, but gray. See the attached screenshot.

<img width="605" alt="Capture" src="https://user-images.githubusercontent.com/5002979/89120300-21387400-d4ad-11ea-94d9-c7608296ca2c.PNG">

**Comment by aFFekopp** [comment]
See https://github.com/aFFekopp/noctis/issues/16 for a workaround. Nothing I can do to fix this, without breaking badges.

**Comment by Draxter** [comment]
Ah, gotcha. Thanks.
