### ISSUE TITLE
Wrong red color gaugh

### ISSUE THREAD

**Issue by magtimmermans** [aFFekopp/noctis#20]
Hi,

The color red is wrong for a gaugh. It is:
   label-badge-red: 'rgba(73,85,108,1)'

should be something like:
  label-badge-red: 'rgba(240,85,108,1)'

**Comment by aFFekopp** [comment]
See #18, #16 and #9 

Here is a way to fix it:
> Now i see that you mean the severity color. The Problem is many theme variables are used in multiple places.
> 
> In 1.7 I changed the label-badge colors to change the color of the badges. The same colors are also used for the gauge-card. This broke the gauge cards.
> 
> I changed some of the badge colors back to what they were before in [1.8](https://github.com/aFFekopp/noctis/releases/tag/1.8), but i can't change `label-badge-red` or else you would get red badges. The problem is if the severity of your gauge card reaches the red color it wont be red.
> 
> What you can do is create another theme. Create a file called `gauge_colors.yaml` in your `themes` folder with the following content
> 
> ```
> gauge_colors:
>   label-badge-red: 'rgba(247,53,67,1)'
>   label-badge-blue: 'rgba(26,137,245,1)'
>   label-badge-green: 'rgba(0,202,139,1)'
>   label-badge-yellow: 'rgba(222,176,107,1)'
> ```
> 
> and then set in your gauge cards
> `theme: gauge_colors`

**Comment by stonith** [comment]
I think I'm running into a similar issue but the workaround above doesn't seem to work. My alarm panel "Armed" icon is normally red but grey in Noctis. Is the alarm card referencing a different label? Thanks.

![image](https://user-images.githubusercontent.com/1230015/117935030-26d2ae00-b2b8-11eb-8e11-659de49a658a.png)

**Comment by aFFekopp** [comment]
It's using `--label-badge-red` which is always a problem. If you have [card-mod](https://github.com/thomasloven/lovelace-card-mod) istalled you can do something like this:

```
- type: alarm-panel
  entity: alarm_control_panel.ha_alarm
  card_mod:
    style: |
      :host {
        --label-badge-red: #f73543;
      }
```

That should fix it.

**Comment by stonith** [comment]
Thanks! Your suggestion worked, but it doesn't work for the popup when I click on the icon. Any suggestions for the popup? Thanks again.

![image](https://user-images.githubusercontent.com/1230015/118217589-a1233f80-b42a-11eb-8962-a6e89d41b548.png)

**Comment by aFFekopp** [comment]
I have added `alarm-color-armed` to the theme, should be fixed in the latest release.
