### ISSUE TITLE
Icon state colors are broken

### ISSUE THREAD

**Issue by m1n3nfux** [aFFekopp/noctis#28]
Since some home assistant update in the past they use different variables for colors. Can you update the theme to use them?

**Comment by aFFekopp** [comment]
Can you please give an example of what's broken. I didn't notice anything on my end.

**Comment by m1n3nfux** [comment]
Some Icons don't use paper-item-icon-active-color anymore, as stated [here](https://community.home-assistant.io/t/2022-12-color-states-are-broken-unusable/499890). As a result the active icons are yellow/amber and don't use the accent-color. I tried to change the variables myself to use the accent-color, but failed miserably. [This](https://imgur.com/a/BAiTfSR)(imgur) is how the icons of switch and light entities look. [Here](https://imgur.com/a/9dDbqse)(imgur) is how it is supposed to look (those are input_boolean entities)

**Comment by aFFekopp** [comment]
I have added some of the new rgb variables. Can you please check, if the latest release fixes it.

**Comment by m1n3nfux** [comment]
Yes it is fixed. Awesome, thank you very much :)
