### ISSUE TITLE
Active Color no longer set by theme

### ISSUE THREAD

**Issue by MrBill12** [aFFekopp/noctis#32]
This might be a duplicate of issue #31 but there were too many colors on that screenshot to understand the issue and expectations.  I do not think this is a duplicate of issue #25 

I use noctis as installed by HACS, but make two personal edits after each update:  
```
ha-card-border-radius: "35px"
border-radius: "35px"
```
(including this information since my screenshots will have rounded corners... but otherwise it's noctis)

Since installing 2023.2.2 Active color hasn't worked as expected.  (I should note however I actually jumped from 2022.10.7 to 2023.2.2... I had no time in Nov/Dec and then was gone most of January) Specifically for most card types I see Yellow as the active color.

Specifically I would expect front door to display as #1A89F5 blue instead of yellow:
![image](https://user-images.githubusercontent.com/11392576/224808650-cc9e1857-14bc-4f08-8147-676391c0562d.png)

Likewise the center "Fireplace" Icon should be #1A89F5 blue instead of yellow:  (The YAML shown is the yellow button.)
![image](https://user-images.githubusercontent.com/11392576/224809971-c267b008-6c5a-4117-b164-500b6cb8b49a.png)

Finally, oddly some add-on cards seem to render as expected, i.e. custom-button card:
![image](https://user-images.githubusercontent.com/11392576/224810949-7082cfcd-4481-4a99-a815-f863ba5204dc.png)

I think the breakage occurs because of this note in the 2023.2.0 release notes: 
> Each entity in the frontend has its own color, which is based on the current entity state. We now have [officially added support](https://www.home-assistant.io/integrations/frontend/#state-color) for themes to customize these.

which leads to this section of the front end docs: https://www.home-assistant.io/integrations/frontend/#state-color

I've tried a few dozen experiments to try to find the actual solution, but I guess I don't understand theme's as well as I thought I did.

**Comment by aFFekopp** [comment]
Thanks for your detailed issue report. I have added those new variables in the latest release. Please check if the colors are correct now, I might have missed something.

**Comment by MrBill12** [comment]
That seems to have corrected the issue :)  Many thanks for fixing it that fast... wish i had told you my guess sooner!
