### ISSUE TITLE
Unreadable text next to sliders

### ISSUE THREAD

**Issue by jeremynoesen** [aFFekopp/noctis#35]
The latest update (2023.12.0) included a change to the frontend that displays text next to sliders to show the value your cursor is at. In this theme, that text is replaced with a white pill. The images below show what I mean.
![Screenshot 2023-12-07 at 9 11 36 PM](https://github.com/aFFekopp/noctis/assets/46114593/1632e857-719b-4ea3-a967-9cc6573f585f)
![Screenshot 2023-12-07 at 9 11 50 PM](https://github.com/aFFekopp/noctis/assets/46114593/89ee9b59-c30d-4d96-9886-4fdc3b966807)

**Comment by aFFekopp** [comment]
Should be fixed in the latest release

**Comment by jeremynoesen** [comment]
Can confirm on my end. Thanks!

**Comment by creeve4** [comment]
Which specific part of [0b81d11](https://github.com/aFFekopp/noctis/commit/0b81d11c7b52a5e18a80784ead5e92d609562cd2) fixes this slider background issue?

**Comment by aFFekopp** [comment]
If I remember correctly it was:

`light-primary-color: 'var(--disabled-text-color)'`
