### ISSUE TITLE
Lovelace Edit UI Popup cards are transparent

### ISSUE THREAD

**Issue by chaptergy** [aFFekopp/noctis#4]
When editing the lovelace ui in the ui-mode all the popup dialog cards are transparent. Presumably the same transparency as the backdrop of those cards.

**Comment by aFFekopp** [comment]
I don't think there is a way to change this. That background ist set by `paper-dialog-background-color` the same as all other popups.

I only use yaml mode. Is the transparency a big problem in the ui editor?

**Comment by chaptergy** [comment]
Unfortunately the transparency is in every popup and makes it hard to read. Probably because it is meant to be used with the blurred background js file? Maybe I'll just fork this projext to customize it.

19 Jan 2020 23:19:38 aFFekopp <notifications@github.com>:

**Comment by aFFekopp** [comment]
You are right I didn't notice it to much with that blur effect. I have made the popups opaque in [1.5](https://github.com/aFFekopp/noctis/releases/tag/1.5), because not erveryone is using the blur effect.
