### ISSUE TITLE
Badge border too vague

### ISSUE THREAD

**Issue by metbril** [aFFekopp/noctis#7]
The badge border is hardly visible. In my opinion it should be a little lighter so that there is more contrast with the background. 

![337F81A7-6EE0-4093-8C5E-43BF8F72DE8D](https://user-images.githubusercontent.com/559346/72867026-d52a9c80-3cdd-11ea-89c4-b0b0619cde2a.jpeg)
![63929CBE-CECA-4936-9289-75C8FEC890BE](https://user-images.githubusercontent.com/559346/72867038-dd82d780-3cdd-11ea-9de2-0a5eb2015322.jpeg)
![96579E72-D2E7-4D55-A00E-510F0FD38EFE](https://user-images.githubusercontent.com/559346/72867048-e4114f00-3cdd-11ea-8c39-82b62e27b236.png)

**Comment by aFFekopp** [comment]
I have increased the visibility of badges in the latest relase. Please check if it is good enough.

**Comment by metbril** [comment]
lgtm

<img width="383" alt="Schermafbeelding 2020-01-22 om 15 39 33" src="https://user-images.githubusercontent.com/559346/72903404-70972e00-3d2d-11ea-8584-3db38e3aa030.png">
