### ISSUE TITLE
Mini player bar

### ISSUE THREAD

**Issue by riemers** [aFFekopp/noctis#8]
![image](https://user-images.githubusercontent.com/682041/72929248-ca155200-3d59-11ea-8847-245bf13038ec.png)

Don't know if it is on your side, but i did see examples on the mini player (https://github.com/kalkih/mini-media-player) and there the bars at the bottom are a distinct color. Now it looks like something is cut of since it almost matches the rest.

**Comment by aFFekopp** [comment]
I don't have this problem, my progress indicator is the blue accent color. I will add mini-media-player theme variables, this should fix it for you.

**Comment by oalbaf** [comment]
I have this problem with input_number


![image](https://user-images.githubusercontent.com/31956250/72935499-c091e700-3d65-11ea-8b0b-262cd2bf6e14.png)

And in Android show number but in PC no.. like the capture

**Comment by aFFekopp** [comment]
> I have this problem with input_number
> 
> ![image](https://user-images.githubusercontent.com/31956250/72935499-c091e700-3d65-11ea-8b0b-262cd2bf6e14.png)
> 
> And in Android show number but in PC no.. like the capture

Can you please create a new issue for this 😃

**Comment by aFFekopp** [comment]
> Don't know if it is on your side, but i did see examples on the mini player (https://github.com/kalkih/mini-media-player) and there the bars at the bottom are a distinct color. Now it looks like something is cut of since it almost matches the rest.

Please see if this is fixed in the newes relase.

**Comment by oalbaf** [comment]
Fixed in 1.9 version!

Thanks!!

**Comment by riemers** [comment]
It is blue for me now, so works like a charm.
